Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if sys.version_info >= (3, 8):
    import importlib.metadata
    extras = importlib.metadata.metadata('openpifpaf').get_all('Provides-Extra')
    print(f'pip3 install "openpifpaf[{",".join(extras)}]"')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-1681635b31b1>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mif[0m [0msys[0m[0;34m.[0m[0mversion_info[0m [0;34m>=[0m [0;34m([0m[0;36m3[0m[0;34m,[0m [0;36m8[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m     [0;32mimport[0m [0mimportlib[0m[0;34m.[0m[0mmetadata[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0mextras[0m [0;34m=[0m [0mimportlib[0m[0;34m.[0m[0mmetadata[0m[0;34m.[0m[0mmetadata[0m[0;34m([0m[0;34m'openpifpaf'[0m[0;34m)[0m[0;34m.[0m[0mget_all[0m[0;34m([0m[0;34m'Provides-Extra'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m     [0mprint[0m[0;34m([0m[0;34mf'pip3 install "openpifpaf[{",".join(extras)}]"'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'sys' is not defined
NameError: name 'sys' is not defined

